### ISSUE TITLE
I built the app... where I should put it?

### ISSUE THREAD

**Issue by tekord** [jahudka/rearrangefx#1]
Hi! Your readme is not clear:

> Download, unzip, run.

So, the repo does not contain any executable app. I downloaded repo, executed `npm install` and run `gulp build`. After that I have `build` folder with all executables. Where I should put these files to work it inside reaper?

**Comment by jahudka** [comment]
Hi, sorry about that, you can get the pre-built packages from http://jahudka.github.io/rearrangefx/, I've updated the readme with a link. But you can use the builds you created yourself, since you already have those. You can put the appropriate build for your platform anywhere you like, it's a standalone app, so on Windows a good place would be e.g. `C:\Program Files`, on a Mac it would be `/Aplications`. You then simply run the app by doubleclicking `RearrangeFX.exe` (on Windows) or the app itself (on a Mac).

**Comment by tekord** [comment]
@jahudka thanks! I run app, see buttons, but they not working. I push "settings" and nothing happened. I also tried to run as administrator, still nothing. Any thoughts?

**Comment by jahudka** [comment]
I don't know.. I think you may have encountered the same issue someone else did a couple of weeks ago, but I never got to the bottom of it.. Could you try running RearrangeFX from the terminal with the `--debug` argument? That should open the developer console and there may be some helpful error messages there..

**Comment by tekord** [comment]
@jahudka unfortunately there is nothing in console after I run app with flag `--debug` :(.

**Comment by jahudka** [comment]
@tekord okay, that sucks.. Could you please clarify what system you're using?

**Comment by tekord** [comment]
@jahudka Windows 8.1 64bit.

**Comment by jahudka** [comment]
Closing as this feature is now available inside REAPER without the need to use this app.
