### ISSUE TITLE
Feature Request?

### ISSUE THREAD

**Issue by adugnasimon** [jahudka/rearrangefx#2]
I would like to request an addition to RearrangeFX for Reaper, which is the ability to alphabetically sort the VSTs within a folder.

**Comment by jahudka** [comment]
Hi, an older version of RearrangeFX used to do that, but Reaper doesn't respect the order of plugins within a folder as defined in the INI file - it just always sorts them according to its own logic - which is why I removed the feature. It was just a source of frustration for people who'd painstakingly sort all of their folders' contents exactly as they wanted them only to find out all their work was lost..

**Comment by adugnasimon** [comment]
Aah right, thanks for explaining.
Hopefully this feature would be made available in Reaper in a future update.
